package org.rpi.player.events;

public enum EnumPlayerEvents {
	
	EVENTBASE,
	EVENTDURATIONUPDATE,
	EVENTFINISHEDCURRENTTRACK,
	EVENTLOADED,
	EVENTSTATUSCHANGED,
	EVENTTIMEUPDATED,
	EVENTTRACKCHANGED, 
	EVENTUPDATETRACKINFO, 
	EVENTUPDATETRACKMETATEXT, 
	EVENTVOLUMECHANGED,
	EVENTAIRPLAYVOLUMECHANGED,
	EVENTRADIOSTATUSCHANGED,
	EVENTRADIOPLAYINGTRACKID,
	EVENTPLAYLISTSTATUSCHANGED,
	EVENTPLAYLISTPLAYINGTRACKID,
	EVENTPLAYLISTUPDATESHUFFLE,
	EVENTMUTECHANGED,
	EVENTSTANDBYCHANGED,
	EVENTRADIOPLAYNAME,
	EVENTCURRENTTRACKFINISHING,
	EVENTSOURCECHANGED,
	EVENTREQUESTVOLUMEINC,
	EVENTREQUESTVOLUMEDEC,
	EVENTRECEIVERSTATUSCHANGED,
	EVENTSTOPSONGCAST,
	EVENTAIRPLAYERPLAYING,
	EVENTAIRPLAYERSTOP
	;
}
