package org.rpi.player.events;

public enum EnumPlayerEvents {
	
	EVENTBASE,
	EVENTDURATIONUPDATE,
	EVENTFINISHEDCURRENTTRACK,
	EVENTLOADED,
	EVENTSTATUSCHANGED,
	EVENTTIMEUPDATED,
	EVENTTRACKCHANGED, 
	EVENTUPDATETRACKINFO, 
	EVENTUPDATETRACKMETATEXT, 
	EVENTVOLUMECHNANGED,
	EVENTRADIOSTATUSCHANGED,
	EVENTRADIOPLAYINGTRACKID,
	EVENTPLAYLISTSTATUSCHANGED,
	EVENTPLAYLISTPLAYINGTRACKID,
	EVENTPLAYLISTUPDATESHUFFLE,
	EVENTMUTECHANGED,
	EVENTSTANDBYCHANGED,
	EVENTRADIOPLAYNAME
	;
}
